language: c
sudo: true

install:
        - sudo apt-get update -y 
        - sudo apt-get install -y libjansson-dev

script:
  - make tests

branches:
    only:
        - master
        - dev

notifications:
    email: false
