language: c
sudo: true

install:
        - sudo apt-get update -y 
        - sudo apt-get install -y libjansson-dev

before_script:
        - mkdir -p unity/build && cd unity/build && cmake .. && cd ../

script:
  - make tests

branches:
    only:
        - master
        - dev

notifications:
    email: false
